research_task:
  description: >
    对{topic}进行彻底研究
    确保你能找到当前年份{current_year}下任何有趣且相关的信息。
  expected_output: >
    一个包含10个要点的列表，列出关于{topic}的最相关信息
  agent: researcher

reporting_task:
  description: >
    审阅你获得的内容，并将每个主题扩展为报告的完整章节。
    确保报告详细且包含所有相关信息。
  expected_output: >
    一份完整的报告，包含主要主题，每个主题都有完整的信息章节。
    以markdown格式呈现，不含'```'标记
  agent: reporting_analyst
